#!/bin/bash

./pluto -i initfiles/beta05.ini > out-raw/beta05.log
./pluto -i initfiles/beta1.ini > out-raw/beta1.log
./pluto -i initfiles/beta01.ini > out-raw/beta01.log
./pluto -i initfiles/beta10.ini > out-raw/beta10.log

