#!/bin/bash

./pluto -i initfiles/low-beta05.ini > out-raw/low-beta05.log
./pluto -i initfiles/low-beta1.ini > out-raw/low-beta1.log
./pluto -i initfiles/low-beta01.ini > out-raw/low-beta01.log
./pluto -i initfiles/low-beta10.ini > out-raw/low-beta10.log

